### ISSUE TITLE
Yaw-pitch-roll in a Z-Up coordinates reference system

### ISSUE THREAD

**Issue by deviloper** [sungiant/abacus#22]
Hi, I'm using abacus in a z-up reference system. 
In order to let it work correctly I replaced rotations as follows:

Y-Up: Yaw axis = Y, Pitch axis = X, Roll axis = Z
Z-Up: Yaw axis = Z (abacus Roll), Pitch axis = Y (abacus Yaw), Roll axis = X (abacus Pitch) 

and it worked but what about the rotation order? 
I suspect it's right for the tranformation of points but it can cause issues when working on objects which need to keep the right up direction. Any idea? Thank you!

**Comment by sungiant** [comment]
Hi deviloper.  Did you solve your issue?  If not, can you provide more of an explanation please?   I'm not sure I understand the question, sorry!
