### ISSUE TITLE
Has Transform been removed?

### ISSUE THREAD

**Issue by JasonTitcomb** [sungiant/abacus#23]
I upgraded from Abacus.0.9.2 to Abacus.1.1.0 using NuGet and it breaks my code.
BC30456	'Transform' is not a member of 'Vector3'
Otherwise, great work on the library.
Please advise.

https://github.com/sungiant/abacus/blob/ff525cedd1df16525ca06269a27e09cd96224dc8/source/abacus/src/main/Abacus.Double.cs#L286

**Comment by JasonTitcomb** [comment]
I changed my code to adapt.

**Comment by JasonTitcomb** [comment]
Something is still broken. I will try to track it down

**Comment by sungiant** [comment]
Hi, perhaps I can help.  Which method had you previously been using?  Any more details would be great.  Thanks.

**Comment by JasonTitcomb** [comment]
Upgrading from 0.9.2 to is a breaking change.
`Abacus.SinglePrecision.Vector3.Transform(fromKeyPoint, viewMat)`

Here is the project I am working on.
https://github.com/JasonTitcomb/Basic_CNC_Viewer/search?q=Vector3.Transform

I re-coded to fix the errors and started to see bed results in the transforms so I backed out.

**Comment by sungiant** [comment]
Took a look; cool project.  I think this was the issue: https://github.com/sungiant/abacus/commit/8a7801ced26ef8ff49b1e2cd419c9234bb6b6502

Fixed now in `1.1.1`.

You can find a snapshot of the older code here if you need it: https://github.com/sungiant/abacus/tree/archive

As for breaking changes relating to the upgrade, the static `Vector3.Transform` method was moved to be a static method of the `Matrix44` class.
